repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.3.4
  hooks:
    # Run the linter.
    - id: ruff
      files: ^src|^test
    # Run the formatter.
    - id: ruff-format
      args: [--check]
      files: ^src|^test
